#!/bin/bash
#
# Do install stuff for armel+dove, including making bootable CDs
# Works with debian-installer
#
# $1 is the CD number
# $2 is the temporary CD build dir
#
# TODO
# - hardcodes flavour

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDDIR=$2
BOOTDIR=
if [ "$DI_WWW_HOME" = "default" ];then
   DI_WWW_HOME="http://people.debian.org/~joeyh/d-i/images/daily"
fi
if [ ! "$DI_DIST" ]; then
   export DI_DIST="$DI_CODENAME"
fi
if [ -z "$DI_PATH" ]; then
   DI_PATH="$($BASEDIR/tools/find-newest-installer)"
fi

default_preseed

cd $CDDIR/..

#
# This script is called with $1 (now $N) as the CD to.
# make bootable.  N may be in the form "n" or "n_NONUS"
# There may be more than 4 disks...support extras.

# Strip NONUS part of disk number
# NN will be 1...N so it can be used as an index
#
NN=`echo $N | sed -e 's/_NONUS//'`

if [ "$CDIMAGE_ADDON" ]; then
    # second disk, at least in spirit
    NN=2
fi

if [ "$IMAGE_FORMAT" = iso ]; then
    echo -n "-J -joliet-long " > $N.mkisofs_opts

    "$BASEDIR/tools/sorting_weights" "$N"
    echo -n "-sort $(pwd)/$N.weights " >> $N.mkisofs_opts
fi

if [ "$IMAGE_FORMAT" != vfat ]; then
    echo "armel booting for image format '$IMAGE_FORMAT' disabled for now"
    exit 0
fi

# XXX hardcodes SUBARCH / FLAVOUR
SUBARCH=dove
FLAVOUR=dove

BOOT_IMAGES="udeb.list $SUBARCH/cdrom/initrd.gz"
DISK_IMAGES=""
TAR_IMAGES=""

# XXX kernel needs to be fixed so that we stop needing this cruft
if [ "$DI_WWW_HOME" ]; then
    echo "boot-armel does not support DI_WWW_HOME mode at the moment" >&2
    exit 1
fi
BOOT_IMAGE_KERNEL=
for vmlinuz in "$DI_PATH/current/images/$SUBARCH/cdrom/vmlinuz"-*-"$FLAVOUR"; do
    BOOT_IMAGE_KERNEL="$SUBARCH/cdrom/$(basename "$vmlinuz")"
done
if [ -z "$BOOT_IMAGE_KERNEL" ]; then
    echo "no kernel found in $DI_PATH/current/images/$SUBARCH/cdrom/!" >&2
    exit 1
fi
BOOT_IMAGES="$BOOT_IMAGES $BOOT_IMAGE_KERNEL"

#### the snippet below was copied from the i386 version
# Download boot images
for image in $BOOT_IMAGES $DISK_IMAGES $TAR_IMAGES; do
    if [ ! -e "$image" ]; then
	dir=$(dirname $image)
	mkdir -p $dir
	if [ ! "$DI_WWW_HOME" ];then
		cp "$DI_PATH/current/images/$image" "$image"
	else
		wget "$DI_WWW_HOME/$image" -O "$image"
	fi
    fi
done

mv $BOOT_IMAGE_KERNEL $SUBARCH/cdrom/vmlinuz

output_boot_script() {
    kernel_addr="0x00200000"
    ramdisk_addr="0x01100000"

    if [ $# != 6 ]; then
        echo "Internal error when calling output_boot_script; got $# args" >&2
        exit 1
    fi
    script_text_file="$1"
    uboot_script_image="$2"
    display_name="$3"
    kernel_path="$4"
    ramdisk_path="$5"
    cmdline_append="$6"

    rm -f "$script_text_file"
    cat >"$script_text_file" <<EOF
echo "Loading $display_name..."
fatload usb 0:1 $kernel_addr $kernel_path
fatload usb 0:1 $ramdisk_addr $ramdisk_path
setenv bootargs console=ttyS0,115200 console=tty0 file=/cdrom/preseed/ubuntu.seed video=dovefb:lcd0:1280x768-24@60 clcd.lcd0_enable=1$cmdline_append
bootm $kernel_addr $ramdisk_addr
EOF
	mkimage -A arm -T script -C none -n 'Ubuntu boot script' -d "$script_text_file" "$uboot_script_image"
	rm -vf "$script_text_file"
}

if [ "$NN" = "1" ]; then
    check_kernel_sync udeb.list $FLAVOUR

    if [ "$CDIMAGE_INSTALL_BASE" = 1 ]; then
	output_boot_script \
	     "$CDDIR/boot.script" "$CDDIR/boot.scr" \
	     "Ubuntu Alternate Installer" \
	     "/cdrom/uImage" "/cdrom/uRamdisk" \
	     ""

	# Discussion with kernel team and ogra has that the kernel will have a uImage
	# and update-initramfs will create a uRamdisk, thus we simply copy these to
	# the saner filenames

	cp -lf $SUBARCH/cdrom/vmlinuz $CDDIR/install/uImage
	cp -lf $SUBARCH/cdrom/initrd.gz $CDDIR/install/uRamdisk
    fi

    if [ "$CDIMAGE_LIVE" = 1 ]; then
	output_boot_script \
	     "$CDDIR/boot.script" "$CDDIR/boot.scr" \
	     "Ubuntu Ubuntu LiveCD" \
	     "/casper/uImage" "/casper/uRamdisk" \
	     "-- casper"
	
	mv $CDDIR/casper/filesystem.kernel-$FLAVOUR $CDDIR/casper/uImage
	CASPER_INITRD="/casper/uRamdisk"
	mv $CDDIR/casper/filesystem.initrd-$FLAVOUR "$CDDIR$CASPER_INITRD"
    fi
fi

# th,th, thats all
