#!/bin/bash
#
# Do install stuff for ppc64el, including making bootable CDs
# Works with debian-installer
#
# $1 is the CD number
# $2 is the temporary CD build dir

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDDIR=$2
INSTALLDIR=$CDDIR/install
if [ ! "$DI_DIST" ]; then
   export DI_DIST="$DI_CODENAME"
fi
if [ -z "$DI_PATH" ]; then
   DI_PATH="$($BASEDIR/tools/find-newest-installer)"
fi

default_preseed
default_language

cd $CDDIR/..

# Only disk 1* bootable
if [ $N != 1 ] && [ $N != 1_NONUS ] && [ -z "$CDIMAGE_ADDON" ]; then
    # we don't need HFS cruft on anything but CD 1
	:> $N.mkisofs_opts
	exit 0
fi

install_languages $CDDIR

echo -n "--netatalk -hfs -probe -map $BASEDIR/data/hfs.map" \
        > $N.mkisofs_opts
echo -n " -chrp-boot -iso-level 4" >> $N.mkisofs_opts
# For newworld Mac booting  - Note, no spaces in volid!
echo -n " -part -no-desktop -hfs-bless CD$N/install -hfs-volid ${CAPPROJECT}_PPC64EL_${CODENAME} " \
	>> $N.mkisofs_opts
# Recommended size for a HFS Catalog is 4 megas per giga, defaults to 4 megas
if [ "$CDIMAGE_DVD" = 1 ]; then
  if [ -n "$SIZELIMIT1" ];then
    if [ "$SIZELIMIT1" -gt 1000000000 ];then
      let newsize="$SIZELIMIT1"/256
      echo -n " -hfs-parms MAX_XTCSIZE=$newsize" >> $N.mkisofs_opts
    fi
  else
    if [ -n "$SIZELIMIT" ];then
      if [ "$SIZELIMIT" -gt 1000000000 ];then
        let newsize="$SIZELIMIT"/256
        echo -n " -hfs-parms MAX_XTCSIZE=$newsize" >> $N.mkisofs_opts
      fi
    else
      if [ -n "$DEFBINSIZE" ] && [ "$DEFBINSIZE" -gt 1000 ];then
        let newsize="$DEFBINSIZE"*4096
        echo -n " -hfs-parms MAX_XTCSIZE=$newsize" >> $N.mkisofs_opts
      fi
    fi
  fi
fi

"$BASEDIR/tools/sorting_weights" "$N"
echo -n " -sort $(pwd)/$N.weights " >> $N.mkisofs_opts

BOOT_IMAGES="cdrom/vmlinux cdrom/initrd.gz cdrom/debian-cd_info.tar.gz"

(cd $CDDIR/..;
 cp -a "$DI_PATH/current/images/MANIFEST.udebs" .
 list_kernel_abis $BOOT_IMAGES | check_kernel_sync)

DI_DIR="$DI_PATH/current/images"
if [ "$CDIMAGE_INSTALL_BASE" = 1 ]; then
  cp -lf "$DI_DIR/cdrom/vmlinux" "$CDDIR/install/"
  cp -lf "$DI_DIR/cdrom/initrd.gz" "$CDDIR/install/"
fi
tar -C "$CDDIR" -xf "$DI_DIR/cdrom/debian-cd_info.tar.gz"

# setup grub menu
sed -i '/^menuentry/Q' $CDDIR/boot/grub/grub.cfg

if [ "$CDIMAGE_INSTALL" = 1 ]; then
cat >> $CDDIR/boot/grub/grub.cfg <<EOF
menuentry "Install $HUMANPROJECT" {
	set gfxpayload=keep
	linux	/install/vmlinuz $KERNEL_PARAMS $DEFAULT_PRESEED quiet ---
	initrd	/install/initrd.gz
}
EOF
fi

if [ "$CDIMAGE_INSTALL_BASE" = 1 ]; then
cat >> $CDDIR/boot/grub/grub.cfg <<EOF
menuentry "Install MAAS Region Controller" {
	set gfxpayload=keep
	linux	/install/vmlinuz $KERNEL_PARAMS modules=maas-region-udeb vga=788 initrd=/install/initrd.gz quiet ---
	initrd	/install/initrd.gz
}

menuentry "Install MAAS Rack Controller" {
	set gfxpayload=keep
	linux	/install/vmlinuz $KERNEL_PARAMS modules=maas-rack-udeb vga=788 initrd=/install/initrd.gz quiet ---
	initrd	/install/initrd.gz
}
EOF
    cat >> $CDDIR/boot/grub/grub.cfg <<EOF
menuentry "Check disc for defects" {
	set gfxpayload=keep
	linux	/install/vmlinuz $KERNEL_PARAMS MENU=/bin/cdrom-checker-menu quiet ---
	initrd	/install/initrd.gz
}
EOF
    cat >> $CDDIR/boot/grub/grub.cfg <<EOF
menuentry "Rescue a broken system" {
	set gfxpayload=keep
	linux	/install/vmlinuz $KERNEL_PARAMS rescue/enable=true ---
	initrd	/install/initrd.gz
}
EOF
fi

exit 0
