#!/bin/bash
#
# boot-s390-common
#
# Common code for s390 and s390x
#
# (C) 2001 Jochen Röhrig <jr@debian.org>
#     2005 Frans Pop <fjp@debian.org>
#     2015-2016 Dimitri John Ledkov <xnox@ubuntu.com> - changes for ubuntu
#
# Released under the GNU general Public License.
# See the copyright file for license details.
# Released as part of the debian_cd package, not much use stand alone.
#
# Install stuff for booting an s390 system from VM-reader, 
# FTP-server, or CD-ROM.
#
# $1 is the CD number
# $2 is the temporary CD build dir

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e
set -x

N=$1
CDDIR=$2
INSTALLDIR=$CDDIR/install
if [ ! "$DI_DIST" ]; then
   export DI_DIST="$DI_CODENAME"
fi
if [ -z "$DI_PATH" ]; then
   DI_PATH="$($BASEDIR/tools/find-newest-installer)"
fi

default_preseed
default_language

cd $CDDIR/..

install_languages $CDDIR

imagedir="boot$N/boot"
mkdir -p $imagedir
DI_DIR="$DI_PATH/current/images"

cp -lf "$DI_DIR/generic/ubuntu.exec" $imagedir
cp -lf "$DI_DIR/generic/ubuntu.ins" $imagedir
cp -lf "$DI_DIR/generic/parmfile.ubuntu" $imagedir
cp -lf "$DI_DIR/generic/initrd.ubuntu" $imagedir
cp -lf "$DI_DIR/generic/kernel.ubuntu" $imagedir
cp -lf "$DI_DIR/generic/initrd.off" $imagedir
cp -lf "$DI_DIR/generic/initrd.siz" $imagedir

hwedir="boot$N/boot-hwe"
if [ -d "$DI_DIR/hwe-generic" ]
then
    mkdir -p $hwedir
    cp -lf "$DI_DIR/hwe-generic/ubuntu.exec" $hwedir
    cp -lf "$DI_DIR/hwe-generic/ubuntu.ins" $hwedir
    cp -lf "$DI_DIR/hwe-generic/parmfile.ubuntu" $hwedir
    cp -lf "$DI_DIR/hwe-generic/initrd.ubuntu" $hwedir
    cp -lf "$DI_DIR/hwe-generic/kernel.ubuntu" $hwedir
    cp -lf "$DI_DIR/hwe-generic/initrd.off" $hwedir
    cp -lf "$DI_DIR/hwe-generic/initrd.siz" $hwedir
fi

$BASEDIR/tools/gen-s390-cd-kernel.pl --initrd=$imagedir/initrd.ubuntu --kernel=$imagedir/kernel.ubuntu --outfile=$imagedir/ubuntu.ikr

cp "$DI_DIR/MANIFEST.udebs" .
list_kernel_abis $images_S390 | check_kernel_sync

# Copy the different boot files
# - ubuntu.ins    : for booting from CD-ROM or FTP-Server
# - README
cp $BASEDIR/data/$CODENAME/$ARCH/* $imagedir
if [ -d $hwedir ]
then
    cp $BASEDIR/data/$CODENAME/$ARCH/* $hwedir
fi

# secondary top-level ubuntu.ins file was requested in
# https://bugs.launchpad.net/ubuntu-cdimage/+bug/1536981/comments/6
sed -e 's,^[^*],boot/&,g' < $imagedir/ubuntu.ins > $imagedir/../ubuntu.ins
if [ -d $hwedir ]
then
    sed -e 's,^[^*],boot-hwe/&,g' < $hwedir/ubuntu.ins > $hwedir/../ubuntu-hwe.ins    
fi

# add_mkisofs_opt is buggy, it thinks "-b" was already "specified" in
# "-no-emul-boot"
#
add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-no-emul-boot -b boot/ubuntu.ikr"

# Include the boot$N/-tree into the iso-image
add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J boot$N"
