#!/bin/bash
#
# boot-hppa
#
# $1 is the CD number
# $2 is the temporary CD build dir

# palo is used to make ISOs bootable on HPPA.

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDROOT=$2
if [ "$DI_WWW_HOME" = "default" ];then
   DI_WWW_HOME="http://people.debian.org/~jbailey/d-i/hppa/daily/cdrom/2.6"
fi
if [ ! "$DI_DIST" ]; then
   DI_DIST="$DI_CODENAME"
fi
if [ -z "$DI_TYPE" ]; then
   DI_TYPE="$($BASEDIR/tools/find-newest-installer)"
fi

case $PROJECT in
    edubuntu)
	DEFAULT_PRESEED='preseed/file=/cdrom/preseed/edubuntu.seed'
	;;
    kubuntu)
	DEFAULT_PRESEED='preseed/file=/cdrom/preseed/kubuntu.seed'
	;;
    ubuntu-server)
	DEFAULT_PRESEED='preseed/file=/cdrom/preseed/ubuntu-server.seed'
	;;
    *)
	DEFAULT_PRESEED=
	;;
esac

:> $1.mkisofs_opts

"$BASEDIR/tools/sorting_weights" "$N"
echo -n "-sort $(pwd)/$N.weights " >> $N.mkisofs_opts

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

PALODEB="$($BASEDIR/tools/apt-selection cache show palo | \
	sed -n 's/^Filename: \(.*_hppa.deb\)$/\1/p')"
ar p "${MIRROR}/${PALODEB}" data.tar.gz | tar xz ./usr/share/palo/iplboot
mv usr/share/palo/iplboot $CDROOT/install/iplboot

if [ ! "$DI_WWW_HOME" ];then
	DI_DIR="$MIRROR/dists/$DI_DIST/main/$DI_TYPE-$ARCH/current/images/cdrom/2.6"
else
	DI_DIR="di_stuff"
	mkdir "$DI_DIR"
	wget -r -nd --no-parent -P "$DI_DIR" "$DI_WWW_HOME"
fi
	
if [ -e "$CDROOT/casper/filesystem.kernel-hppa32" ]; then
	mv "$CDROOT/casper/filesystem.kernel-hppa32" "$CDROOT/install/vmlinux-hppa32"
else
	cp "$DI_DIR"/vmlinux-*-hppa32 "$CDROOT/install/vmlinux-hppa32"
fi
if [ -e "$CDROOT/casper/filesystem.kernel-hppa64" ]; then
	mv "$CDROOT/casper/filesystem.kernel-hppa64" "$CDROOT/install/vmlinux-hppa64"
else
	cp "$DI_DIR"/vmlinux-*-hppa64 "$CDROOT/install/vmlinux-hppa64"
fi
# TODO: we're screwed here, because mkisofs only supports one ramdisk. Pick
# hppa32 arbitrarily for now.
if [ -e "$CDROOT/casper/filesystem.initrd-hppa32" ]; then
	mv "$CDROOT/casper/filesystem.initrd-hppa32" "$CDROOT/install/initrd.gz"
else
	cp "$DI_DIR"/initrd.gz "$CDROOT/install"
fi

install_languages "$CDROOT"

if [ "$CDIMAGE_LIVE" = 1 ]; then
    EXTRA_ARGS='boot=casper,splash'
else
    EXTRA_ARGS=
fi

echo " -hppa-cmdline 0/vmlinux,${DEFAULT_PRESEED:+$DEFAULT_PRESEED,}${EXTRA_ARGS:+$EXTRA_ARGS,}root=/dev/ram,initrd=0/ramdisk,ramdisk_size=1048576" >> $1.mkisofs_opts
echo " -hppa-kernel-32 install/vmlinux-hppa32" >> $1.mkisofs_opts
echo " -hppa-kernel-64 install/vmlinux-hppa64" >> $1.mkisofs_opts
echo " -hppa-bootloader install/iplboot" >> $1.mkisofs_opts
echo " -hppa-ramdisk install/initrd.gz" >> $1.mkisofs_opts

exit 0
