#! /bin/sh -e

BDIR=$TDIR/$CODENAME-$FULLARCH

mkdir -p "$BDIR/CD1/casper"
if [ -e "$LIVEIMAGES/$ARCH.cloop" ]; then
	ln "$LIVEIMAGES/$ARCH.cloop" "$BDIR/CD1/casper/filesystem.cloop"
elif [ -e "$LIVEIMAGES/$ARCH.squashfs" ]; then
	ln "$LIVEIMAGES/$ARCH.squashfs" "$BDIR/CD1/casper/filesystem.squashfs"
else
	echo "No filesystem for $ARCH!" >&2
fi
for item in kernel initrd; do
	for path in "$LIVEIMAGES/$ARCH.$item"-*; do
		if [ -f "$path" ]; then
			ln "$path" "$BDIR/CD1/casper/filesystem.${path#$LIVEIMAGES/$ARCH.}"
		fi
	done
done
ln "$LIVEIMAGES/$ARCH.manifest" "$BDIR/CD1/casper/filesystem.manifest" || true
ln "$LIVEIMAGES/$ARCH.manifest-desktop" "$BDIR/CD1/casper/filesystem.manifest-desktop" || true

if [ -f "$LIVEIMAGES/$ARCH.winfoss.tgz" ]; then
	tar -C "$BDIR/CD1" -xzf "$LIVEIMAGES/$ARCH.winfoss.tgz"
	if [ -e "$BDIR/CD1/programs/firefox/Firefox Setup 1.0.exe" ]; then
		mv "$BDIR/CD1/programs/firefox/Firefox Setup 1.0.exe" \
			"$BDIR/CD1/programs/firefox/FirefoxSetup1.0.exe"
	fi
	if [ -e "$BDIR/CD1/programs/thunderbird/Thunderbird Setup 1.0.exe" ]; then
		mv "$BDIR/CD1/programs/thunderbird/Thunderbird Setup 1.0.exe" \
			"$BDIR/CD1/programs/thunderbird/ThunderbirdSetup-1.0.exe"
	fi
fi
