#!/bin/sh

# Create the needed directories before putting packages into them

set -e

# There's no difference between NONFREE and EXTRANONFREE for this script
if [ "${EXTRANONFREE:-0}" != "0" ]
then
    NONFREE=1
fi

cd $1

if [ ! -e ubuntu ] ; then
    ln -sf . ubuntu
fi

if [ ! -d dists/$CODENAME ] ; then
    mkdir -p dists/$CODENAME
    for name in stable unstable; do
	ln -sf $CODENAME dists/$name
    done
fi

# Commodity link for tools which want local in dists/local/local ...
if [ -n "$LOCAL" ]
then
    ln -sf $CODENAME dists/local
fi


if [ ! -d .disk ] ; then
    mkdir .disk
fi

ALL_ARCHES="$ARCH"
if [ -e "$BASEDIR/data/$CODENAME/multiarch/$ARCH" ]; then
  ALL_ARCHES="$ALL_ARCHES $(cat "$BASEDIR/data/$CODENAME/multiarch/$ARCH")"
fi

for ONE_ARCH in $ALL_ARCHES; do
    mkdir -p dists/$CODENAME/main/binary-$ONE_ARCH
done
mkdir -p dists/$CODENAME/main/source
if [ "${CONTRIB:-0}" != 0 ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/contrib/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/contrib/source
fi
if [ "${NONFREE:-0}" != "0" ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/non-free/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/non-free/source
fi
if [ "${RESTRICTED:-0}" != "0" ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/restricted/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/restricted/source
fi
if [ "${UNIVERSE:-0}" != "0" ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/universe/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/universe/source
fi
if [ "${MULTIVERSE:-0}" != "0" ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/multiverse/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/multiverse/source
fi

if [ -n "$LOCAL"  -a -e "${LOCALDEBS:-$MIRROR}/dists/$DI_CODENAME/local/debian-installer" ]; then
    mkdir -p dists/$CODENAME/local/debian-installer/binary-$ARCH
fi
if [ -e "$MIRROR/dists/$DI_CODENAME/main/debian-installer" ]; then
    mkdir -p dists/$CODENAME/main/debian-installer/binary-$ARCH
fi
if [ "${RESTRICTED:-0}" != "0" ] && \
   [ -e "$MIRROR/dists/$DI_CODENAME/restricted/debian-installer" ]; then
    mkdir -p dists/$CODENAME/restricted/debian-installer/binary-$ARCH
fi
if [ "${UNIVERSE:-0}" != "0" ] && \
   [ -e "$MIRROR/dists/$DI_CODENAME/universe/debian-installer" ]; then
    mkdir -p dists/$CODENAME/universe/debian-installer/binary-$ARCH
fi
    
if [ -n "$NONUS" ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/non-US/main/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/non-US/main/source
    if [ "${CONTRIB:-0}" != "0" ]; then
	for ONE_ARCH in $ALL_ARCHES; do
	    mkdir -p dists/$CODENAME/non-US/contrib/binary-$ONE_ARCH
	done
        mkdir -p dists/$CODENAME/non-US/contrib/source
    fi
    if [ "${NONFREE:-0}" != "0" ]; then
	    for ONE_ARCH in $ALL_ARCHES; do
		mkdir -p dists/$CODENAME/non-US/non-free/binary-$ONE_ARCH
	    done
	    mkdir -p dists/$CODENAME/non-US/non-free/source
    fi
    if [ "${RESTRICTED:-0}" != "0" ]; then
	    for ONE_ARCH in $ALL_ARCHES; do
		mkdir -p dists/$CODENAME/non-US/restricted/binary-$ONE_ARCH
	    done
	    mkdir -p dists/$CODENAME/non-US/restricted/source
    fi
    if [ "${UNIVERSE:-0}" != "0" ]; then
	    for ONE_ARCH in $ALL_ARCHES; do
		mkdir -p dists/$CODENAME/non-US/universe/binary-$ONE_ARCH
	    done
	    mkdir -p dists/$CODENAME/non-US/universe/source
    fi
    if [ "${MULTIVERSE:-0}" != "0" ]; then
	    for ONE_ARCH in $ALL_ARCHES; do
		mkdir -p dists/$CODENAME/non-US/multiverse/binary-$ONE_ARCH
	    done
	    mkdir -p dists/$CODENAME/non-US/multiverse/source
    fi
fi

if [ -n "$LOCAL" ]; then
    for ONE_ARCH in $ALL_ARCHES; do
	mkdir -p dists/$CODENAME/local/binary-$ONE_ARCH
    done
    mkdir -p dists/$CODENAME/local/source
fi
