#! /bin/sh -e

BDIR=$TDIR/$CODENAME-$FULLARCH

mkdir -p "$BDIR/CD1/casper"
if [ -e "$LIVEIMAGES/$FULLARCH.cloop" ]; then
	ln "$LIVEIMAGES/$FULLARCH.cloop" "$BDIR/CD1/casper/filesystem.cloop"
elif [ -e "$LIVEIMAGES/$FULLARCH.squashfs" ]; then
	ln "$LIVEIMAGES/$FULLARCH.squashfs" "$BDIR/CD1/casper/filesystem.squashfs"
	if [ -e "$LIVEIMAGES/$FULLARCH.size" ]; then
		ln "$LIVEIMAGES/$FULLARCH.size" "$BDIR/CD1/casper/filesystem.size"
	fi
else
	echo "No filesystem for $FULLARCH!" >&2
fi
if [ -e "$LIVEIMAGES/$FULLARCH.usb-creator.exe" ]; then
	ln "$LIVEIMAGES/$FULLARCH.usb-creator.exe" "$BDIR/CD1/usb-creator.exe"
fi
for item in kernel initrd; do
	for path in "$LIVEIMAGES/$FULLARCH.$item"-*; do
		if [ -f "$path" ]; then
			ln "$path" "$BDIR/CD1/casper/filesystem.${path#$LIVEIMAGES/$FULLARCH.}"
		fi
	done
done
ln "$LIVEIMAGES/$FULLARCH.manifest" "$BDIR/CD1/casper/filesystem.manifest" || true
if [ -e "$LIVEIMAGES/$FULLARCH.manifest-remove" ]; then
	ln "$LIVEIMAGES/$FULLARCH.manifest-remove" "$BDIR/CD1/casper/filesystem.manifest-remove" || true
else
	ln "$LIVEIMAGES/$FULLARCH.manifest-desktop" "$BDIR/CD1/casper/filesystem.manifest-desktop" || true
fi

if [ "$PROJECT" = edubuntu ] && [ "$CDIMAGE_DVD" = 1 ]; then
	case $ARCH in
		amd64|i386)
			mkdir -p "$BDIR/CD1/ltsp"
			# LTSP is i386 for both architectures
			ln "$LIVEIMAGES/$FULLARCH.ltsp-squashfs" "$BDIR/CD1/ltsp/i386.img"
			;;
	esac
fi

lzcat_sane () {
	lzcat -S '' "$@"
}

initrd_decompressor () {
	if zcat -t "$1" >/dev/null 2>&1; then
		echo zcat
	elif bzcat -t "$1" >/dev/null 2>&1; then
		echo bzcat
	elif lzcat_sane -t "$1" >/dev/null 2>&1; then
		echo lzcat_sane
	fi
}

# Extract the UUID from the casper initrd, if any.
mkdir -p "$BDIR/uuid"
for path in "$BDIR/CD1/casper/filesystem.initrd"-*; do (
	[ -e "$path" ] || continue
	cd "$BDIR/uuid"
	decompressor="$(initrd_decompressor "$path")"
	[ "$decompressor" ] || continue
	"$decompressor" "$path" | cpio --quiet -id conf/uuid.conf
	if [ -e conf/uuid.conf ]; then
		mkdir -p "$BDIR/CD1/.disk"
		mv conf/uuid.conf "$BDIR/CD1/.disk/casper-uuid-${path#$BDIR/CD1/casper/filesystem.initrd-}"
	fi
); done

# Release notes URL for use by Ubiquity. '${LANG}' will be replaced with the
# installation locale code.
RELEASE_NOTES=
case $PROJECT in
	ubuntu|kubuntu|edubuntu|xubuntu|gobuntu)
		case $DIST in
			warty|hoary|breezy|dapper|edgy)
				;;
			*)
				RELEASE_NOTES="http://www.ubuntu.com/getubuntu/releasenotes?os=$PROJECT&ver=${DEBVERSION%% *}&lang=\${LANG}"
				;;
		esac
		;;
esac
if [ "$RELEASE_NOTES" ]; then
	mkdir -p "$BDIR/CD1/.disk"
	echo "$RELEASE_NOTES" > "$BDIR/CD1/.disk/release_notes_url"
fi
