#! /bin/sh -e

BDIR=$TDIR/$CODENAME-$FULLARCH

mkdir -p "$BDIR/CD1/casper"
if [ -e "$LIVEIMAGES/$ARCH.cloop" ]; then
	ln "$LIVEIMAGES/$ARCH.cloop" "$BDIR/CD1/casper/filesystem.cloop"
elif [ -e "$LIVEIMAGES/$ARCH.squashfs" ]; then
	ln "$LIVEIMAGES/$ARCH.squashfs" "$BDIR/CD1/casper/filesystem.squashfs"
else
	echo "No filesystem for $ARCH!" >&2
fi
for item in kernel initrd; do
	for path in "$LIVEIMAGES/$ARCH.$item"-*; do
		if [ -f "$path" ]; then
			ln "$path" "$BDIR/CD1/casper/filesystem.${path#$LIVEIMAGES/$ARCH.}"
		fi
	done
done
ln "$LIVEIMAGES/$ARCH.manifest" "$BDIR/CD1/casper/filesystem.manifest" || true
ln "$LIVEIMAGES/$ARCH.manifest-desktop" "$BDIR/CD1/casper/filesystem.manifest-desktop" || true

# Release notes URL for use by Ubiquity. '${LANG}' will be replaced with the
# installation locale code.
case $PROJECT in
	ubuntu|kubuntu|edubuntu|xubuntu)
		case $DIST in
			feisty)
				RELEASE_NOTES="http://www.ubuntu.com/products/GetUbuntu/ReleaseNotes?os=$PROJECT&ver=$DEBVERSION&lang=\${LANG}"
				;;
		esac
		;;
esac
