#!/bin/bash
#
# Do install stuff for armel+omap, including making bootable CDs
# Works with debian-installer
#
# $1 is the CD number
# $2 is the temporary CD build dir
#
# TODO
# - hardcodes flavour

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDDIR=$2
BOOTDIR=
if [ "$DI_WWW_HOME" = "default" ];then
   DI_WWW_HOME="http://people.debian.org/~joeyh/d-i/images/daily"
fi
if [ ! "$DI_DIST" ]; then
   export DI_DIST="$DI_CODENAME"
fi
if [ -z "$DI_PATH" ]; then
   DI_PATH="$($BASEDIR/tools/find-newest-installer)"
fi

default_preseed

cd $CDDIR/..

#
# This script is called with $1 (now $N) as the CD to.
# make bootable.  N may be in the form "n" or "n_NONUS"
# There may be more than 4 disks...support extras.

# Strip NONUS part of disk number
# NN will be 1...N so it can be used as an index
#
NN=`echo $N | sed -e 's/_NONUS//'`

if [ "$CDIMAGE_ADDON" ]; then
    # second disk, at least in spirit
    NN=2
fi

if [ "$IMAGE_FORMAT" = iso ]; then
    echo -n "-J -joliet-long " > $N.mkisofs_opts

    "$BASEDIR/tools/sorting_weights" "$N"
    echo -n "-sort $(pwd)/$N.weights " >> $N.mkisofs_opts
fi

if [ "$IMAGE_FORMAT" != vfat ]; then
    echo "armel booting for image format '$IMAGE_FORMAT' disabled for now"
    exit 0
fi

# XXX hardcodes SUBARCH / FLAVOUR
SUBARCH=omap
FLAVOUR=omap

BOOT_IMAGES="$SUBARCH/cdrom/initrd.gz"
DISK_IMAGES=""
TAR_IMAGES=""

if [ "$DI_WWW_HOME" ]; then
    echo "boot-armel does not support DI_WWW_HOME mode at the moment" >&2
    exit 1
fi
BOOT_IMAGE_KERNEL=`cd "$DI_PATH/current/images" && ls $SUBARCH/cdrom/vmlinuz*`
if [ -z "$BOOT_IMAGE_KERNEL" ]; then
    echo "no kernel found in $DI_PATH/current/images/$SUBARCH/cdrom/!" >&2
    exit 1
fi
BOOT_IMAGES="$BOOT_IMAGES $BOOT_IMAGE_KERNEL"

#### the snippet below was copied from the i386 version
# Download boot images
for image in MANIFEST.udebs $BOOT_IMAGES $DISK_IMAGES $TAR_IMAGES; do
    if [ ! -e "$image" ]; then
	dir=$(dirname $image)
	mkdir -p $dir
	if [ ! "$DI_WWW_HOME" ];then
		cp "$DI_PATH/current/images/$image" "$image"
	else
		wget "$DI_WWW_HOME/$image" -O "$image"
	fi
    fi
done

if [ "$BOOT_IMAGE_KERNEL" != "$SUBARCH/cdrom/vmlinuz" ]; then
    mv "$BOOT_IMAGE_KERNEL" "$SUBARCH/cdrom/vmlinuz"
fi

if [ "$NN" = "1" ]; then
    list_kernel_abis $BOOT_IMAGES | check_kernel_sync $FLAVOUR

    do_uboot=0
    if [ "$CDIMAGE_INSTALL_BASE" = 1 ]; then
	do_uboot=1
	uboot_desc="Ubuntu Alternate Installer"
	uboot_input_kernel="$CDDIR/cdrom/uImage.in"
	uboot_input_initrd="$CDDIR/cdrom/uInitrd.in"
	uboot_kernel="/cdrom/uImage"
	uboot_initrd="/cdrom/uInitrd"
	uboot_extra_cmdline=" cdrom-detect/try-usb=true"

	mkdir -p "`dirname "$uboot_input_kernel"`"
	cp -lf "$SUBARCH/cdrom/vmlinuz"   "$uboot_input_kernel"
	cp -lf "$SUBARCH/cdrom/initrd.gz" "$uboot_input_initrd"
    fi

    if [ "$CDIMAGE_LIVE" = 1 ]; then
	do_uboot=1
	uboot_desc="Ubuntu LiveCD"
	uboot_input_kernel="$CDDIR/casper/filesystem.kernel-$FLAVOUR"
	uboot_input_initrd="$CDDIR/casper/filesystem.initrd-$FLAVOUR"
	uboot_kernel="/casper/uImage"
	uboot_initrd="/casper/uInitrd"
	uboot_extra_cmdline=" -- boot=casper only-ubiquity nocompcache"
    fi

    if [ "$do_uboot" ]; then
	uboot_script_text="$CDDIR/boot.script"
	uboot_script_image="$CDDIR/boot.scr"
	uboot_kernel_addr="0x80000000"
	uboot_ramdisk_addr="0x81600000"
	uboot_script_addr="0x1000"

	rm -f "$uboot_script_text"
cat >"$uboot_script_text" <<EOF
	fatload mmc 0:1 $uboot_kernel_addr $uboot_kernel
	fatload mmc 0:1 $uboot_ramdisk_addr $uboot_initrd
	setenv bootargs quiet splash vram=12M omapfb.mode=dvi:1280x720MR-16@60 $DEFAULT_PRESEED $uboot_extra_cmdline
	bootm $uboot_kernel_addr $uboot_ramdisk_addr
EOF
	mkimage -A arm -T script -C none -n "Ubuntu boot script" -d "$uboot_script_text" "$uboot_script_image"
	rm -vf "$uboot_script_text"

	rm -f "$CDDIR/$uboot_kernel"
	mkimage -A arm -O linux -T kernel -C none -a 0x80008000 -e 0x80008000 -n "Ubuntu Kernel" -d "$uboot_input_kernel" "$CDDIR/$uboot_kernel"
	rm -vf "$uboot_input_kernel"

	rm -f "$CDDIR/$uboot_initrd"
	mkimage -A arm -O linux -T ramdisk -C none -a 0x0 -e 0x0 -n "Ubuntu Initrd" -d "$uboot_input_initrd" "$CDDIR/$uboot_initrd"
	rm -vf "$uboot_input_initrd"
    fi
fi

# th,th, thats all
